apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge
  template:
    metadata:
      labels:
        app: judge
    spec:
      containers:
        - name: yuoj-backend-judge-service
          image: lc-yuoj-backend-judge-service  # 改成你的镜像名称
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8104  # 容器内部服务监听的端口
          resources:
            requests:
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: judge-service
spec:
  selector:
    app: judge
  ports:
    - protocol: TCP
      port: 8104         # 外部暴露的端口
      targetPort: 8104   # Pod 内的服务端口
  type: ClusterIP        # 使用 NodePort 直接暴露端口
